stages:
    - build
    - test

    
    
build:
    stage: build
    script:
        - echo "HelloWorld"
        
test:
    stage: test
    script:
        - echo "test quality"
        
code quality:
    stage: test
    script:
        - echo "code quality"
        