stages:
    - build
    - test
    - staging
    - production
    - performance
    
    
build:
    stage: build
    script:
        - echo "HelloWorld"
        
test:
    stage: code quality
    script:
        - echo "test quality"